<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DT-AKASH" name="com.healthec.provider.test.smoke.TestInstantMessengerUC_003" tests="3" failures="0" timestamp="21 Mar 2017 10:57:06 GMT" time="1.448" errors="1">
  <testcase name="IMTC_001" time="0.000" classname="com.healthec.provider.test.smoke.TestInstantMessengerUC_003">
    <skipped/>
  </testcase> <!-- IMTC_001 -->
  <testcase name="beforeImtest" time="1.448" classname="com.healthec.provider.test.smoke.TestInstantMessengerUC_003">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.healthec.provider.ui.Loginpage.<init>(Loginpage.java:16)
	at com.healthec.provider.test.smoke.TestLoginUC_001.setUp(TestLoginUC_001.java:26)
	at com.healthec.provider.test.smoke.TestdashboardUC_002.beforedashboardTC(TestdashboardUC_002.java:24)
	at com.healthec.provider.test.smoke.TestInstantMessengerUC_003.beforeImtest(TestInstantMessengerUC_003.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.beforeRun(TestRunner.java:626)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- beforeImtest -->
  <testcase name="IMTC_002" time="0.000" classname="com.healthec.provider.test.smoke.TestInstantMessengerUC_003">
    <skipped/>
  </testcase> <!-- IMTC_002 -->
</testsuite> <!-- com.healthec.provider.test.smoke.TestInstantMessengerUC_003 -->
